### ISSUE TITLE
if...then...else :: fill a column based on a condition

### ISSUE THREAD

**Issue by vdestraitt** [ToucanToco/toucan-data-sdk#26]
The API could look something like this:

```
if_then_else:
    if: query string (like in our `query` postprocess)
    then: formula (like in our `formula` postprocess) or string or boolean or number
    else: formula (like in our `formula` postprocess) or string or boolean or number
    new_column: string
```
